# Generated by Django 4.2.2 on 2023-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
