# Generated by Django 4.2.2 on 2023-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pizza_active_alter_pizza_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('premium', 'Premium'), ('basic', 'Basic')], max_length=7),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
